# Generated by Django 2.0.9 on 2018-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('team_name', models.CharField(max_length=30)),
                ('opponent', models.CharField(max_length=30)),
                ('player', models.PositiveSmallIntegerField()),
                ('fgm', models.PositiveSmallIntegerField(default=0)),
                ('fga', models.PositiveSmallIntegerField(default=0)),
                ('threepm', models.PositiveSmallIntegerField(default=0)),
                ('threepa', models.PositiveSmallIntegerField(default=0)),
                ('ftm', models.PositiveSmallIntegerField(default=0)),
                ('fta', models.PositiveSmallIntegerField(default=0)),
                ('oreb', models.PositiveSmallIntegerField(default=0)),
                ('dreb', models.PositiveSmallIntegerField(default=0)),
                ('ast', models.PositiveSmallIntegerField(default=0)),
                ('stl', models.PositiveSmallIntegerField(default=0)),
                ('blk', models.PositiveSmallIntegerField(default=0)),
                ('tov', models.PositiveSmallIntegerField(default=0)),
                ('pf', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
