# Generated by Django 2.0.9 on 2018-12-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_under_game', models.CharField(max_length=30)),
                ('us', models.CharField(max_length=30)),
                ('opponent', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_cap', models.CharField(max_length=30)),
                ('team_name_under_Team', models.CharField(max_length=30)),
            ],
        ),
    ]
