# Generated by Django 2.1.3 on 2018-12-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxscore', '0003_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetime',
            name='user',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
