# Generated by Django 2.1.3 on 2018-12-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxscore', '0004_lifetime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetime',
            name='games',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
